### ISSUE TITLE
Stuck on processing with no data displayed for PlanetScale

### ISSUE THREAD

**Issue by jakst** [vercel-labs/edge-data-latency#12]
The PlanetScale test does not seem to work. It says processing, but does not display any data. I tried every type of query.

All the other tests work fine for me.

![Screenshot_20230315-183109.png](https://user-images.githubusercontent.com/3687893/225393291-d677a8e0-be08-4655-874c-afe3e81c04e8.png)

**Comment by leerob** [comment]
Hey! This was likely due to the PlanetScale DB going to sleep when inactive. It currently needs to be "woke up" when it spins down. Apologies for this.
